### ISSUE TITLE
No HID-device in PC can be found 

### ISSUE THREAD

**Issue by Dieterxu** [Fabi019/hid-barcode-scanner#18]
After connection in the Info Tag,  there are three services: Audio, Capture, Networking.  But no HID-service.

**Comment by Fabi019** [comment]
The data shown in the Info dialog is only intended for debugging purposes and displays the capabilities of the currently connected device. Because of that this will show no HID service.
Are you able to send values from the phone to the connected PC? On the PC side the phone should show up as a Keyboard. You can confirm if this is the case by checking in the device manager on windows for example and looking under the category Keyboards. There should be a "HID Keyboard Device" with its location set to "on Bluetooth HID Device".

**Comment by Dieterxu** [comment]
> The data shown in the Info dialog is only intended for debugging purposes and displays the capabilities of the currently connected device. Because of that this will show no HID service. Are you able to send values from the phone to the connected PC? On the PC side the phone should show up as a Keyboard. You can confirm if this is the case by checking in the device manager on windows for example and looking under the category Keyboards. There should be a "HID Keyboard Device" with its location set to "on Bluetooth HID Device".

Actually, no. I tried a few things but couldn't get it to work. In "Bluetooth" category, it shows the three devices associated with the phone name, but no HID device. Under "Keyboard" I can't see any change when the phone connected or disconnected. Maybe need it a driver? thx.

**Comment by Fabi019** [comment]
You can try to unpair/remove the other device on both the PC and the phone. Then from within the app scan for new devices and connect with the PC. This should trigger a pair request and after confirmation setup the HID device on the PC.

**Comment by Dieterxu** [comment]
Within the app I can find the PC, but after clicking happens nothing. It seems the trigger is not transferred to the PC.

**Comment by Fabi019** [comment]
Is there a loading screen when clicking on the device? And did you also remove the phone on the PC side? Otherwise it might end up in a weird situation where the PC still knows the phone but the phone doesn't.
If this still does not help. I would suggest you to try out a different app that allows the phone to act like a Keyboard/Mouse just to confirm if it is a general problem between the device/PC or with this App in particular. A possible candidate for testing would be this App for example: <https://play.google.com/store/apps/details?id=io.appground.blek>. If you are able to control your PC with an App like this, I can then investigate further why it does not work with my App.
