### ISSUE TITLE
Don't send STX

### ISSUE THREAD

**Issue by vikh1976** [Fabi019/hid-barcode-scanner#250]
I'm trying to send STX+CODE+ETX+ENTER

Custom template looks like {+B}{CODE}{+C}{ENTER}, but Ctrl+B (STX) don't send. 

Is it possible to send? Or is any way to send hex before the code?

Thanks.

**Comment by Fabi019** [comment]
Hi, thanks for reaching out. I looked at your provided example and the issue could be caused by the uppercase B and C.
With the uppercase letters it not only sends a CTRL+B but instead implicitly does a CTRL+SHIFT+B to achieve the uppercase.
So you could try out your template with lowecase letters instead and see if that works: `{+b}{CODE}{+c}{ENTER}`.
Let me know if that solved your issue.

**Comment by vikh1976** [comment]
Hi! 

No, that didn't help at all. And if at least {+C} in template send ETX, {+c} sends nothing. 

I tried to send barcode to Notepad++ with all sybols enabled

Screen 
![Screenshot_4](https://github.com/user-attachments/assets/9ee49dc9-e594-47ce-85af-9fed4a47b5ad)
