### ISSUE TITLE
Couldn't scan some barcode

### ISSUE THREAD

**Issue by Indranil012** [Fabi019/hid-barcode-scanner#71]
I have attached the barcode which is not getting scanned properly with this app. but working with others app like binary eye.
![IMG_20230508_165108](https://user-images.githubusercontent.com/48489074/236837709-02e243e8-ed23-49a4-9340-3338216a5cae.jpg)

**Comment by Fabi019** [comment]
Hi, thank you for your feedback and providing me with the sample.
It seems like the code can be scanned with the app, but only if the scan resolution in the settings is set to 720p+. This could be because of the relatively thin lines in the barcode, as other samples of simmilar types can be scanned without any problem even on the lowest resolution.
I will check if it is possible to tweak the default camera settings a bit to make it easier for the scanner to register the code. Also I will probably update the default setting for the scan resolution to 720p as there is not that much of a performance difference.

**Comment by Indranil012** [comment]
Thank you for the information. Great app. 🙏

**Comment by Fabi019** [comment]
The newest version now contains a setting for fixing the camera exposure and iso. This should help to detect these codes more easily. For the PlayStore I will release it first in the beta-branch, but push it soon to production.
